// <auto-generated />
namespace ePro.DB.applicationdbcontext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialcreate4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialcreate4));
        
        string IMigrationMetadata.Id
        {
            get { return "201507061116051_initialcreate4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
